services:
  # PostgreSQL Database
  - type: pserv
    name: cryptonews-db
    env: python
    plan: free
    region: oregon
    databases:
      - name: cryptonews_db
        databaseName: cryptonews
        user: cryptonews_user

  # Telegram Bot Service
  - type: worker
    name: cryptonews-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      # Telegram Configuration
      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: TELEGRAM_CHANNEL_ID
        sync: false

      # News API Keys
      - key: NEWSAPI_KEY
        sync: false

      - key: CRYPTOPANIC_API_KEY
        sync: false

      - key: CRYPTOCOMPARE_API_KEY
        sync: false

      # Google Gemini API
      - key: GEMINI_API_KEY
        sync: false

      # Database Configuration (auto-populated by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: cryptonews-db
          property: connectionString

      # Scheduler Configuration (Legacy - not used for real-time posting)
      - key: POSTING_HOUR
        value: "9"

      - key: POSTING_MINUTE
        value: "0"

      - key: TIMEZONE
        value: "UTC"

      # Real-Time News Monitoring Configuration
      - key: ENABLE_REALTIME_POSTING
        value: "true"

      - key: NEWS_CHECK_INTERVAL_MINUTES
        value: "5"

      - key: MIN_IMPORTANCE_SCORE
        value: "7"

      # Subscription & Payment Configuration
      - key: TRIAL_DAYS
        value: "15"

      - key: SUBSCRIPTION_PRICE_USD
        value: "15.00"

      - key: GRACE_PERIOD_DAYS
        value: "3"

      # NOWPayments API Configuration
      - key: NOWPAYMENTS_API_KEY
        sync: false

      - key: NOWPAYMENTS_IPN_SECRET
        sync: false

      - key: WEBHOOK_URL
        sync: false

      - key: WEBHOOK_PORT
        value: "8080"

      - key: SUPPORTED_CURRENCIES
        value: "btc,eth,usdt,usdc,bnb,trx"

      - key: PAYMENT_INVOICE_EXPIRATION_MINUTES
        value: "60"

      # Logging
      - key: LOG_LEVEL
        value: "INFO"

      # Python Environment
      - key: PYTHON_VERSION
        value: "3.11"

